### PR TITLE
Full gitignore, travis ci setup file, readme badge and codacy edits

### PR DESCRIPTION
**Pull request by SamSamhuns**

### CODE REVIEW

**Comment by 4shadoww** [comment]
Could you add to the key bindings section new key bindings: key "u" for volume up and "d" for volume down? I forgot to do that update to the read me when I made #5 pull request.

**Comment by SamSamhuns** [comment]
> Could you add to the key bindings section new key bindings: key "u" for volume up and "d" for volume down? I forgot to do that update to the read me when I made #5 pull request.

Done.

**Comment by ceoro9** [comment]
@SamSamhuns also in readme under installation section, version of packages are out-dated. Can you please make them correspond the `requirements.txt`. But to be fair I would rather completely remove such installation option, idk.

**Comment by SamSamhuns** [comment]
> @SamSamhuns also in readme under installation section, version of packages are out-dated. Can you please make them correspond the `requirements.txt`. But to be fair I would rather completely remove such installation option, idk.

Yes, I believe it is better to remove the version numbers in the req. These packages should be backward compatible in updated versions.

**Comment by vaibkumr** [comment]
Thank you everyone for your contributions!

**Pull request merged**
